### ISSUE TITLE
Let's finish the exercise!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-natalia-pn#2]
Cool job @natalia-pn !!!

Here you have some tips to improve the exercise:

- [ ] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [ ] Use a `label` to define the content of the input
- [ ] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [ ] Use placeholder attribute instead of value one to show a field's hint
- [ ] Define the logic to make the counter work
- [ ] Remember to convert input value string to a number
- [ ] Extract the feedback painter to a function
- [ ] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
- [ ] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number
- [ ] Move variables declaration to the top of the file
- [ ] Use `===` instead of `==` for comparisons
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [ ] Remove commented code

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by natalia-pn** [comment]
Thanks @oneeyedman!!

Just pushed all the changes! Let me know if there's anything else that I should fix, so I can merge both branches.

**Comment by oneeyedman** [comment]
Super good job @natalia-pn!!
Merge the Click-counter branch to Master when you are ready.

Here, have a Well Done gif!
![Well done](https://media.giphy.com/media/3o7TKF5DnsSLv4zVBu/giphy-tumblr.gif)
